language: python
python:
  - "2.7"
  - "3.8"
  # PyPy versions
  - "pypy"
  - "pypy3"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
# command to run tests
script: test/UnitTests.py
